name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: agilira/workflow/.github/workflows/go-ci-full.yml@v1
    with:
      go-version: 'stable'
      gosec-config: '.gosec.json'
